name: CI

on:
  pull_request:
    types: [synchronize, opened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          tags: test
          load: true
          target: develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: test
        run: docker run test cargo test
